CREATE TABLE ETAT_SANTE (
    idEtatSante TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(30)
);

CREATE TABLE PERSONNE (
    idPersonne TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(15),
    prenom VARCHAR(15),
    joursFaim TINYINT UNSIGNED,
    joursSoif TINYINT UNSIGNED,
    sanite TINYINT UNSIGNED,
    A_ETAT_SANTE TINYINT UNSIGNED,
    FOREIGN KEY (A_ETAT_SANTE) REFERENCES ETAT_SANTE(idEtatSante)
);

CREATE TABLE OBJET (
    idObjet TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(30),
    consommable TINYINT
);