CREATE TABLE MyCharacter (
    idPersonne TINYINT UNSIGNED PRIMARY KEY,
    nom VARCHAR(15),
    joursFaim TINYINT UNSIGNED,
    joursSoif TINYINT UNSIGNED,
    etatSante TINYINT UNSIGNED
);

CREATE TABLE MyItem (
    idObjet TINYINT UNSIGNED PRIMARY KEY,
    nom VARCHAR(30),
    tag VARCHAR(15)
);